nitrond: fixup!: fix problematic syntax issues
Signed-off-by: UsiFX <xprjkts@gmail.com>

diff --git a/nitrond b/nitrond
--- a/nitrond
+++ b/nitrond
@@ -357,13 +357,13 @@ updaten()
 		echo "[$(date +%I:%M:%S)] $0: ${arg#*}: pinging 8.8.8.8 ..." >> $NITRON_LOG_DIR/nitron.log
 		if [[ $(ping -c1 "8.8.8.8" > /dev/null && echo $?) == '0' ]]
   		then
-    		echo "[$(date +%I:%M:%S)] $0: ${arg#*}: failed, returned to $?" >> $NITRON_LOG_DIR/nitron.log
-    		return $?
+			echo "[$(date +%I:%M:%S)] $0: ${arg#*}: failed, returned to $?" >> $NITRON_LOG_DIR/nitron.log
+			return $?
   		else
-    		printn -i "looking for update..."
-    		wget -O "/cache/nitrond_src_cache" "https://raw.githubusercontent.com/UsiFX/OpenNitroN/main/nitrond"
-    		if diff "$0" "/cache/nitrond_src_cache"
-    		then
+			printn -i "looking for update..."
+			wget -O "/cache/nitrond_src_cache" "https://raw.githubusercontent.com/UsiFX/OpenNitroN/main/nitrond"
+			if diff "$0" "/cache/nitrond_src_cache"
+			then
       			printn -i "updating..."
       			cat "/cache/nitrond_src_cache" > $0
       			printn -n "updated successfully."
@@ -372,7 +372,7 @@ updaten()
       			printn -n "up to date."
       			return $?
     		fi
-  		fi
+		fi
 	fi
 }
 
