Rewrite printn
** hm

Signed-off-by: Pedrozzz0 <guitopzika26@gmail.com>

diff --git a/nitrond b/nitrond
--- a/nitrond
+++ b/nitrond
@@ -37,16 +37,17 @@ PROMPT_COMMAND='sync'
 } || source $(pwd)/nitron_headers.sh
 
 printn() {
-	case "${printn_opts}" in
-			n) printf "[${BLUE}*${STOCK}] $2\n" ;;
-			e)
-				printf "[${RED}×${STOCK}] $2\n"
-				return 1
-				;;
-			w) printf "[${YELLOW}!${STOCK}] $2\n" ;;
-			i) printf "[${CYAN}i${STOCK}] $2 \n" ;;
-		esac
-}
+	[[ "$1" == "n" ]] && printf "[${BLUE}*${STOCK}] $2\n" ;;
+	
+	[[ "$1" == "e" ]] && {
+	printf "[${RED}×${STOCK}] $2\n"
+	return 1
+	}
+	
+	[[ "$1" == "w" ]] && printf "[${YELLOW}!${STOCK}] $2\n"
+	
+	[[ "$1" == "i" ]] && printf "[${CYAN}i${STOCK}] $2 \n" ;;
+}	
 
 writen() {
 	[[ ! -f "$1" ]] && {
@@ -357,21 +358,14 @@ updaten() {
 		echo "[$(date +%I:%M:%S)] $0: ${arg#*}: NITRON_FORCECHECK_UPDATE == ${NITRON_FORCECHECK_UPDATE}" >>$NITRON_LOG_DIR/nitron.log
 		return 1
 	} || echo "[$(date +%I:%M:%S)] $0: ${arg#*}: pinging 8.8.8.8 ..." >>$NITRON_LOG_DIR/nitron.log
-	[[ "$(ping -c1 "8.8.8.8" >/dev/null && echo $?)" == "0" ]] && {
-		echo "[$(date +%I:%M:%S)] $0: ${arg#*}: failed, returned to $?" >>$NITRON_LOG_DIR/nitron.log
-		return $?
-	} || {
+	[[ "$(ping -c1 "8.8.8.8" >/dev/null && echo $?)" == "0" ]] && echo "[$(date +%I:%M:%S)] $0: ${arg#*}: failed" >>$NITRON_LOG_DIR/nitron.log || {
 		printn -i "looking for update..."
 		curl -o "/cache/nitrond_src_cache" "https://raw.githubusercontent.com/UsiFX/OpenNitroN/main/nitrond"
 		[[ "$(diff "$0" "/cache/nitrond_src_cache")" ]] && {
 			printn -i "updating..."
 			cat "/cache/nitrond_src_cache" >$0
 			printn -n "updated successfully."
-			return $?
-		} || {
-			printn -n "up to date."
-			return $?
-		}
+		} || printn -n "up to date."
 	}
 }
 
